# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convert_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CouponData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_data', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PresentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_id', models.IntegerField(default=0)),
                ('pres_name', models.CharField(max_length=200)),
                ('pres_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PushData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='pushdata',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Regist.UserInformation'),
        ),
        migrations.AddField(
            model_name='coupondata',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Regist.UserInformation'),
        ),
        migrations.AddField(
            model_name='convertdata',
            name='pres_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Regist.PresentInformation'),
        ),
        migrations.AddField(
            model_name='convertdata',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Regist.UserInformation'),
        ),
    ]
