# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regist', '0002_userinformation_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='roles',
            field=models.CharField(max_length=200),
        ),
    ]
