# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regist', '0003_auto_20170629_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdata',
            name='date_info',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pushdata',
            name='month',
            field=models.CharField(default='', max_length=200),
        ),
    ]
