# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regist', '0004_auto_20170630_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushdata',
            name='uid',
            field=models.CharField(max_length=200),
        ),
    ]
